### ISSUE TITLE
Support three letter codes

### ISSUE THREAD

**Issue by ftyers** [meikidd/iso-639-1#15]
Would it be possible to add three letter codes ? There are some downstream apps (e.g. Mozilla's [voice-web](https://github.com/mozilla/voice-web/issues/1320)) that would benefit from it. I can make an initial pull request (see #16).

**Comment by ftyers** [comment]
I also generated a list of codes with English names [here](https://file.io/IhlgGs).

**Comment by meikidd** [comment]
> Would it be possible to add three letter codes ?

In my understanding, ISO 639-1 is specially for two-letter codes, where as ISO 639-2 is for three-letter codes. It seems for me we shouldn't add three letter codes into this package since its name is `iso-639-1`. I found another package which support ISO 639-1/2/3, it may cover your requirement -> [adlawson/nodejs-langs](https://github.com/adlawson/nodejs-langs)

Reference: 
- [List of ISO 639-1 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)
- [Language codes - ISO 639](https://www.iso.org/iso-639-language-codes.html)

**Comment by meikidd** [comment]
> I also generated a list of codes with English names here.

Cant reach the link to file.io 😂 
![image](https://user-images.githubusercontent.com/376338/44246520-2d1fc280-a211-11e8-89a8-35c8a9b3b7f0.png)
