### ISSUE TITLE
FEATURE: Capitalize the first letter of all languages

### ISSUE THREAD

**Issue by ghost** [meikidd/iso-639-1#29]
For example, `catalan` is lowercase, and I need all uppercase native names

**Comment by meikidd** [comment]
Hi @Hugovidafe , are you a catalan native speaker? if so, feel free to make a PR.

From my perspective, I can't tell whether those native names are uppercase or not. Some of them don't even have a uppercase, such as "অসমীয়া", "日本語", "中文".

**Comment by Hugovidafe** [comment]
For catalan, is better uppercased De: meikiddEnviado: lunes, 11 de mayo de 2020 14:47Para: meikidd/iso-639-1CC: HUGOVIDAFE; MentionAsunto: Re: [meikidd/iso-639-1] FEATURE: Capitalize the first letter of all languages (#29) Hi @Hugovidafe , are you a catalan native speaker? if so, feel free to make a PR.From my perspective, I can't tell whether those native names are uppercase or not. Some of them don't even have a uppercase, such as "অসমীয়া", "日本語", "中文".—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ghost** [comment]
For catalan, is better uppercased

**Comment by ghost** [comment]
And all native names that start with a letter of the Latin alphabet can start with the first letter in uppercase

**Comment by meikidd** [comment]
v2.1.2 released

**Comment by ghost** [comment]
Not only Catalan, it was an example...

**Comment by vlinder** [comment]
Opened #32, not sure why not all latin alphabet names have a capital first letter? Used in a list by themselves almost all probably should be.. maybe not as often if used in sentences.
